const grid=document.querySelector('#tech-grid'),list=document.querySelector('#stack-list'),count=document.querySelector('#count'),search=document.querySelector('#search'),clear=document.querySelector('#clear'),toast=document.querySelector('#toast');let technologies=[],stack=[],category='All';
const icons={React:'⚛️','Node.js':'🟢',TypeScript:'🔷','MongoDB':'🍃','Tailwind CSS':'🌬️',Docker:'🐳',Git:'🔀',Python:'🐍',PostgreSQL:'🐘','Next.js':'▲'};
function notify(message){toast.textContent=message;toast.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.classList.remove('show'),2200)}
function visible(){const q=search.value.toLowerCase();return technologies.filter(t=>(category==='All'||t.category===category)&&(t.name+' '+t.category+' '+t.description).toLowerCase().includes(q))}
function render(items=visible()){grid.innerHTML=items.length?items.map(t=>{const added=stack.some(x=>x.id===t.id);return `<article class="card"><div class="card-icon">${icons[t.name]||'🧩'}</div><span class="tag">${t.badge}</span><h3>${t.name}</h3><p>${t.description}</p><div class="meta"><span>${t.category}</span><span>★ ${t.rating} · ${t.difficulty}</span></div><button class="add" data-id="${t.id}" ${added?'disabled':''}>${added?'✓ Added to Stack':'＋ Add to Stack'}</button></article>`}).join(''):'<p class="empty">No technologies found. Try another search.</p>';grid.querySelectorAll('.add').forEach(b=>b.addEventListener('click',()=>add(b.dataset.id)))}
function renderStack(){count.textContent=`${stack.length} selected`;list.innerHTML=stack.length?stack.map(t=>`<div class="stack-item"><span>${icons[t.name]||'🧩'}</span><div><strong>${t.name}</strong><br><small>${t.category}</small></div><button class="remove" data-id="${t.id}" aria-label="Remove ${t.name}">×</button></div>`).join(''):'<p class="empty">Your stack is empty.<br><small>Choose technologies to get started.</small></p>';list.querySelectorAll('.remove').forEach(b=>b.addEventListener('click',()=>removeItem(b.dataset.id)))}
function add(id){if(stack.some(t=>t.id===id)){notify('This technology is already in your stack.');return}const t=technologies.find(x=>x.id===id);if(t){stack.push(t);render();renderStack();notify(`${t.name} added to your stack ✓`)}}
function removeItem(id){const t=stack.find(x=>x.id===id);stack=stack.filter(x=>x.id!==id);render();renderStack();if(t)notify(`${t.name} removed from your stack`) }
clear.addEventListener('click',()=>{if(!stack.length){notify('Your stack is already empty.');return}stack=[];render();renderStack();notify('All technologies removed')});search.addEventListener('input',()=>render());document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.category;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()}));document.querySelector('#menu').addEventListener('click',()=>document.querySelector('#nav').classList.toggle('open'));
fetch('data.json').then(r=>{if(!r.ok)throw Error('load');return r.json()}).then(data=>{technologies=data;render();renderStack()}).catch(()=>grid.innerHTML='<p class="empty">Could not load technology data. Please refresh.</p>');
