import { useEffect, useState } from 'react';
import { toast } from 'react-toastify';

export default function App(){
 const [techs,setTechs]=useState([]),[stack,setStack]=useState([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[menu,setMenu]=useState(false);
 useEffect(()=>{fetch('/data.json').then(r=>r.json()).then(setTechs).catch(()=>toast.error('Could not load technologies')).finally(()=>setLoading(false))},[]);
 const add=t=>{if(stack.some(x=>x.id===t.id))return toast.warning(`${t.name} is already in your stack`);setStack([...stack,t]);toast.success(`${t.name} added to your stack`)};
 const remove=t=>{setStack(stack.filter(x=>x.id!==t.id));toast.info(`${t.name} removed`)};
 const filtered=techs.filter(t=>(`${t.name} ${t.category} ${t.description}`).toLowerCase().includes(query.toLowerCase()));
 return <><header><a className="logo" href="#home">Dev<span>Stack</span></a><nav className={menu?'open':''}>{['Home','Technologies','Projects','About','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase()} onClick={()=>setMenu(false)}>{x}</a>)}</nav><div className="auth"><button className="signin">Sign In</button><button>Sign Up</button></div><button className="hamb" onClick={()=>setMenu(!menu)}>☰</button></header>
 <main><section className="hero" id="home"><div><small>BUILD YOUR FUTURE</small><h1>Build your perfect <span>developer stack.</span></h1><p>Discover the technologies that power modern products and create a stack that matches your goals.</p><div><a className="primary" href="#technologies">Explore Technologies →</a><a className="secondary" href="#about">Learn More</a></div></div><div className="hero-art">&lt;/&gt;<i>⌘</i></div></section>
 <section className="section" id="technologies"><div className="section-head"><div><small>EXPLORE THE ECOSYSTEM</small><h2>Choose your technologies</h2><p>Pick the tools that belong in your next project.</p></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="⌕ Search technologies..."/></div><div className="layout"><div className="grid">{loading?<div className="loading">⏳ Loading technologies...</div>:filtered.map(t=><article className="card" key={t.id}><div className="card-top"><img src={t.icon} alt=""/><span>{t.badge}</span></div><h3>{t.name}</h3><p>{t.description}</p><div className="meta"><b>{t.category}</b><span>★ {t.rating}</span></div><small>{t.difficulty}</small><button className="add" disabled={stack.some(x=>x.id===t.id)} onClick={()=>add(t)}>{stack.some(x=>x.id===t.id)?'✓ Added to Stack':'＋ Add to Stack'}</button></article>)}</div><aside><div className="stack-head"><h2>Your Stack</h2><span>{stack.length} selected</span></div>{stack.length===0?<p className="empty">Your stack is empty.<br/>Choose technologies to get started.</p>:stack.map(t=><div className="stack-item" key={t.id}><img src={t.icon} alt=""/><div><b>{t.name}</b><small>{t.category}</small></div><button onClick={()=>remove(t)}>×</button></div>)}<button className="clear" onClick={()=>{if(stack.length){setStack([]);toast.info('Stack cleared')}}}>Remove All</button></aside></div></section>
 <section className="about" id="about"><small>WHY DEVSTACK?</small><h2>Made for curious developers.</h2><p>Explore, compare, and organize the tools you need to build great software.</p></section></main><footer><div><a className="logo" href="#home">Dev<span>Stack</span></a><p>Your toolkit for building the future.</p></div><div><b>Product</b><a href="#technologies">Technologies</a><a href="#projects">Projects</a></div><div><b>Company</b><a href="#about">About</a><a href="#contact">Contact</a></div><div><b>Legal</b><a href="#privacy">Privacy</a><a href="#terms">Terms</a></div><p className="copy">© 2026 DevStack. Built with curiosity.</p></footer></>;
}
